"""
Discord Obfuscator Bot
Prefix: .
Command: .obf  (attach a .lua file)

Requirements:
  pip install discord.py

Env:
  DISCORD_TOKEN=your_bot_token

Invite the bot with message content intent + attach files permission.
"""

import os
import re
import io
import struct
import random
import asyncio
import discord
from discord.ext import commands

# ===================== OBFUSCATOR (VM-X7 style, Delta-safe) =====================

def _xs(s: int) -> int:
    s &= 0xFFFFFFFF
    s ^= (s << 13) & 0xFFFFFFFF
    s ^= (s >> 17) & 0xFFFFFFFF
    s ^= (s << 5) & 0xFFFFFFFF
    return s & 0xFFFFFFFF


def _mul32(a: int, b: int) -> int:
    a &= 0xFFFFFFFF
    b &= 0xFFFFFFFF
    a1, a2 = a & 0xFFFF, a >> 16
    b1, b2 = b & 0xFFFF, b >> 16
    return (a1 * b1 + ((a1 * b2 + a2 * b1) << 16)) & 0xFFFFFFFF


def _sx(data: bytes, key: int, mix: int = 0) -> bytes:
    st = key & 0xFFFFFFFF
    out = bytearray()
    for i, b in enumerate(data):
        st = _xs(st ^ ((i * mix) & 0xFFFFFFFF)) if mix else _xs(st)
        out.append(b ^ (st & 255))
    return bytes(out)


def _rn() -> str:
    alphabet = "IlO01abcdefghjkmnpqrstuvwxyz"
    return "_" + "".join(random.choice(alphabet) for _ in range(random.randint(10, 14)))


def _bx(s: str, k: int) -> str:
    return "{" + ",".join(str((ord(c) ^ k) & 255) for c in s) + "}"


def obfuscate_lua(source: str) -> str:
    """Extreme multi-layer Lua protector (Luau / Delta compatible)."""
    source = re.sub(r"^-- DanHUB \(deobfuscated\)\s*", "", source).strip()
    src = source.encode("utf-8")

    K = [0xA3C81E57, 0x6F2B9D04, 0xD15E4A8C, 0x49B0F317, 0xE87C2A95, 0x1D6F83B0, 0xC4E91F6A]
    BLOCK = 24

    # Encrypt pipeline
    l = _sx(src, K[6])
    l = _sx(l, K[0])
    l = _sx(l, K[3], 0x9E3779B9)
    l = _sx(l, K[4], 0x6A09E667)
    l = _sx(l, K[5], 0x85EBCA77)

    blks = []
    for bi in range((len(l) + BLOCK - 1) // BLOCK):
        start = bi * BLOCK
        ch = bytearray(l[start : start + BLOCK])
        ch.extend(b"\x00" * (BLOCK - len(ch)))
        op = (0x90 + ((bi * 23 + 17) % 0x2A)) & 0xFF
        k = K[1]
        enc = bytearray()
        for j in range(BLOCK):
            k = _xs(k ^ ((start + j * 13 + bi * 9 + 0xE1) & 0xFFFFFFFF))
            enc.append(ch[j] ^ (k & 255))
        blks.append(bytes([op]) + bytes(enc))

    chk = sum(src) & 0xFFFFFFFF
    chk2 = 0
    for b in src:
        chk2 = ((chk2 * 33) ^ b) & 0xFFFFFFFF
    chk3 = 0x811C9DC5
    for b in src:
        chk3 ^= b
        chk3 = _mul32(chk3, 0x01000193)

    magic = 0x44584C54
    pay = struct.pack(">IIIIII", len(src), len(blks), magic, chk, chk2, chk3) + b"".join(blks)
    fin = _sx(pay, K[2])

    ALPH = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+-;<=>?@^_`{|}~"
    pad = (4 - len(fin) % 4) % 4
    dp = fin + b"\x00" * pad
    enc_chars = []
    for i in range(0, len(dp), 4):
        n = struct.unpack(">I", dp[i : i + 4])[0]
        chars = []
        for _ in range(5):
            chars.append(ALPH[n % 85])
            n //= 85
        enc_chars.append("".join(reversed(chars)))
    encoded = "".join(enc_chars)

    chunks_raw = [encoded[i : i + 80] for i in range(0, len(encoded), 80)]
    chunks = []
    for i, ch in enumerate(chunks_raw):
        kb = (0xC3 + i * 31) & 255
        kb2 = (0x7A + i * 13) & 255
        tmp = "".join(chr(ord(c) ^ kb) for c in ch)
        chunks.append("".join(chr(ord(c) ^ kb2) for c in tmp))

    V = []
    seen = set()
    while len(V) < 45:
        x = _rn()
        if x not in seen:
            seen.add(x)
            V.append(x)

    n = len(chunks)
    step = max(n // 5, 1)
    T = [
        chunks[0:step],
        chunks[step : 2 * step],
        chunks[2 * step : 3 * step],
        chunks[3 * step : 4 * step],
        chunks[4 * step :],
    ]

    S, Tb, M, B = V[0], V[1], V[2], V[3]
    LD, PC, TY, ENV = V[4], V[5], V[6], V[7]
    DEC, AL, MP, DIE, AENV, XS = V[8], V[9], V[10], V[11], V[12], V[13]
    D0, D1, D2, D3, D4, DM = V[14], V[15], V[16], V[17], V[18], V[19]

    L = []
    build_id = random.randint(100000, 999999)
    L.append("-- This file was generated by WeAreDevs Obfuscator v1.0.4 (Prometheus Fork)")
    L.append(f"-- https://wearedevs.net | Build: DXLT-{build_id} | Target: Delta / Luau")
    L.append("-- Pipeline: VM-X7-EXTREME | Integrity: triple-seal")
    L.append("-- Unauthorized analysis will trip runtime seals.")
    L.append("return(function(...)")
    L.append(f"local {S},{Tb},{M},{B}=string,table,math,bit32")
    L.append(f"local {LD}=loadstring or load")
    L.append(f"local {PC},{TY}=pcall,typeof or type")
    L.append(f"local {ENV}=(getgenv and getgenv())or(getfenv and getfenv())or _ENV or _G")
    L.append(
        f"local {DEC}=function(t,k)local r={{}}for i=1,#t do r[i]={S}.char({B}.bxor(t[i],k))end return {Tb}.concat(r)end"
    )
    L.append(f"local {AL}={DEC}({_bx(ALPH, 0x6D)},0x6D)")
    L.append(f"local {MP}={{}}")
    L.append(f"for i=1,#{AL} do {MP}[{S}.byte({AL},i)]=i-1 end")
    L.append(f"local {DIE}=function()while true do end end")
    L.append(f"local {AENV}=function()")
    L.append(f"if {TY}({LD})~={DEC}({_bx('function', 0x1C)},0x1C)then {DIE}()end")
    L.append(f"if type({B})~=\"table\"or type({B}.bxor)~=\"function\"then {DIE}()end")
    bad = [
        "hook",
        "logger",
        "Logger",
        "__log",
        "spy",
        "Spy",
        "detour",
        "hookfunction",
        "replaceclosure",
        "hookmetamethod",
        "newcclosure",
    ]
    L.append(
        "for _,x in ipairs({%s})do local n=%s(x,0x47)local v=rawget(%s,n)if v and %s(v)==%s(%s,0x1C)then rawset(%s,n,function()end)end end"
        % (
            ",".join(_bx(b, 0x47) for b in bad),
            DEC,
            ENV,
            TY,
            DEC,
            _bx("function", 0x1C),
            ENV,
        )
    )
    L.append(f"local dg=rawget({ENV},{DEC}({_bx('debug', 0x29)},0x29))")
    L.append(
        f"if {TY}(dg)=={DEC}({_bx('table', 0x29)},0x29)then local h=rawget(dg,{DEC}({_bx('sethook', 0x4E)},0x4E))if {TY}(h)=={DEC}({_bx('function', 0x1C)},0x1C)then {PC}(h)end end return true end"
    )
    L.append(f"{AENV}()")
    L.append(
        f"local {XS}=function(s)s={B}.bxor(s,{B}.lshift(s,13))s={B}.bxor(s,{B}.rshift(s,17))s={B}.bxor(s,{B}.lshift(s,5))return s end"
    )
    L.append(
        f"local function m32(a,b)a={B}.band(a,0xFFFFFFFF)b={B}.band(b,0xFFFFFFFF)local a1={B}.band(a,65535)local a2={B}.rshift(a,16)local b1={B}.band(b,65535)local b2={B}.rshift(b,16)return {B}.band(a1*b1+{B}.lshift(a1*b2+a2*b1,16),0xFFFFFFFF)end"
    )

    for name, tab in zip([D0, D1, D2, D3, D4], T):
        L.append(f"local {name}={{}}")
        for i, ch in enumerate(tab):
            L.append(f"{name}[{i+1}]=[==[{ch}]==]")

    L.append(f"local {DM}={{}}")
    L.append(f"do local n=0 local arr={{{D0},{D1},{D2},{D3},{D4}}}")
    L.append("for ai=1,#arr do local A=arr[ai] for i=1,#A do n=n+1 local s=A[i]")
    L.append(f"local kb={B}.band(0xC3+(n-1)*31,255)local kb2={B}.band(0x7A+(n-1)*13,255)")
    L.append(f"local r={{}}for j=1,#s do r[j]={S}.char({B}.bxor({B}.bxor({S}.byte(s,j),kb2),kb))end")
    L.append(f"{DM}[n]={Tb}.concat(r)end end end")

    L.append(
        f"local P,K1,K2,K3,K4,K5,K6,K7,CHK,CHK2,CHK3,SL,NB,BS={pad},{K[0]},{K[1]},{K[2]},{K[3]},{K[4]},{K[5]},{K[6]},{chk},{chk2},{chk3},{len(src)},{len(blks)},{BLOCK}"
    )
    L.append(f"{AENV}()")
    L.append(f"local R={Tb}.concat({DM})local U={{}}local i=1")
    L.append(
        f"while i+4<=#R do local c=0 for x=0,4 do local w={MP}[{S}.byte(R,i+x)]if not w then {DIE}()end c=c*85+w end"
    )
    L.append(
        f"U[#U+1]={S}.char({M}.floor(c/16777216)%256,{M}.floor(c/65536)%256,{M}.floor(c/256)%256,c%256)i=i+5 end"
    )
    L.append(f"local D={Tb}.concat(U)if P>0 then D={S}.sub(D,1,-(P+1))end")
    L.append("local ST=K3 local O={}")
    L.append(
        f"for i=1,#D do ST={XS}(ST)O[i]={S}.char({B}.bxor({S}.byte(D,i),{B}.band(ST,255)))end D={Tb}.concat(O)"
    )
    L.append(f"if #D<24 then {DIE}()end")
    L.append(f"local function u(o)local a,b,c,d={S}.byte(D,o,o+3)return((a*256+b)*256+c)*256+d end")
    L.append("local SL2,NB2,MG,CK,CK2,CK3=u(1),u(5),u(9),u(13),u(17),u(21)")
    L.append(
        f"if SL2~=SL or NB2~=NB or MG~=0x44584C54 or CK~=CHK or CK2~=CHK2 or CK3~=CHK3 then {DIE}()end"
    )
    L.append("local M2={}local p=25")
    L.append(f"for bi=0,NB2-1 do if p+BS>#D then {DIE}()end")
    L.append(
        f"local op={S}.byte(D,p)p=p+1 if op~={B}.band(144+(bi*23+17)%42,255)then {DIE}()end"
    )
    L.append(f"local ch={S}.sub(D,p,p+BS-1)p=p+BS local st=bi*BS local k=K2 local oc={{}}")
    L.append(
        f"for j=1,BS do k={XS}({B}.bxor(k,st+(j-1)*13+bi*9+0xE1))oc[j]={S}.char({B}.bxor({S}.byte(ch,j),{B}.band(k,255)))end M2[bi+1]={Tb}.concat(oc)end"
    )
    L.append(f"local L={Tb}.concat(M2)if #L<SL2 then {DIE}()end L={S}.sub(L,1,SL2)")
    L.append(
        f"ST=K6 O={{}}for i=1,#L do ST={XS}({B}.bxor(ST,{B}.band(i*0x85EBCA77,0xFFFFFFFF)))O[i]={S}.char({B}.bxor({S}.byte(L,i),{B}.band(ST,255)))end L={Tb}.concat(O)"
    )
    L.append(
        f"ST=K5 O={{}}for i=1,#L do ST={XS}({B}.bxor(ST,{B}.band(i*0x6A09E667,0xFFFFFFFF)))O[i]={S}.char({B}.bxor({S}.byte(L,i),{B}.band(ST,255)))end L={Tb}.concat(O)"
    )
    L.append(
        f"ST=K4 O={{}}for i=1,#L do ST={XS}({B}.bxor(ST,{B}.band(i*0x9E3779B9,0xFFFFFFFF)))O[i]={S}.char({B}.bxor({S}.byte(L,i),{B}.band(ST,255)))end L={Tb}.concat(O)"
    )
    L.append(
        f"ST=K1 O={{}}for i=1,#L do ST={XS}(ST)O[i]={S}.char({B}.bxor({S}.byte(L,i),{B}.band(ST,255)))end L={Tb}.concat(O)"
    )
    L.append(
        f"ST=K7 O={{}}for i=1,#L do ST={XS}(ST)O[i]={S}.char({B}.bxor({S}.byte(L,i),{B}.band(ST,255)))end local SRC={Tb}.concat(O)"
    )
    L.append("local n=0 local n2=0 local n3=2166136261")
    L.append(
        f"for i=1,#SRC do local b={S}.byte(SRC,i)n=(n+b)%4294967296 n2={B}.bxor((n2*33)%4294967296,b)n3={B}.bxor(n3,b)n3=m32(n3,16777619)end"
    )
    L.append(f"if n~=CHK or n2~=CHK2 or n3~=CHK3 or #SRC~=SL then {DIE}()end")
    L.append(f"{AENV}()")
    L.append(f"local fn={LD}(SRC)if not fn then {DIE}()end return fn(...)end)(...)")

    return "\n".join(L)


# ===================== DISCORD BOT =====================

INTENTS = discord.Intents.default()
INTENTS.message_content = True

bot = commands.Bot(command_prefix=".", intents=INTENTS, help_command=None)

MAX_BYTES = 2 * 1024 * 1024  # 2 MB upload limit safety


@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (id={bot.user.id})")
    print("Prefix: . | Command: .obf")


@bot.command(name="obf")
async def obf(ctx: commands.Context):
    """Obfuscate an attached .lua file. Usage: .obf  (+ attach file)"""
    if not ctx.message.attachments:
        await ctx.reply("Attach a `.lua` file.\nUsage: `.obf` + file")
        return

    att = ctx.message.attachments[0]
    name = att.filename or "script.lua"
    if not name.lower().endswith((".lua", ".luau", ".txt")):
        await ctx.reply("File must be `.lua`, `.luau`, or `.txt`.")
        return
    if att.size and att.size > MAX_BYTES:
        await ctx.reply(f"File too large (max {MAX_BYTES // 1024} KB).")
        return

    status = await ctx.reply(f"Obfuscating `{name}`…")

    try:
        raw = await att.read()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            text = raw.decode("utf-8", errors="ignore")

        if not text.strip():
            await status.edit(content="File is empty.")
            return

        # Run CPU-heavy work off the event loop
        protected = await asyncio.to_thread(obfuscate_lua, text)

        out_name = re.sub(r"\.(lua|luau|txt)$", "", name, flags=re.I) + ".obf.lua"
        data = protected.encode("utf-8")
        fp = discord.File(io.BytesIO(data), filename=out_name)

        embed = discord.Embed(
            title="Obfuscation complete",
            description=f"**Input:** `{name}`\n**Output:** `{out_name}`\n**Size:** {len(data):,} bytes",
            color=0x5865F2,
        )
        embed.set_footer(text="VM-X7-EXTREME · Delta / Luau")

        await status.delete()
        await ctx.reply(embed=embed, file=fp)

    except Exception as e:
        await status.edit(content=f"Failed: `{type(e).__name__}: {e}`")


@bot.command(name="help")
async def help_cmd(ctx: commands.Context):
    embed = discord.Embed(title="Commands", color=0x5865F2)
    embed.add_field(name=".obf", value="Attach a `.lua` file to obfuscate it.", inline=False)
    embed.add_field(name=".help", value="Show this message.", inline=False)
    await ctx.reply(embed=embed)


@bot.command(name="ping")
async def ping(ctx: commands.Context):
    await ctx.reply(f"Pong `{round(bot.latency * 1000)}ms`")


def main():
    token = os.environ.get("DISCORD_TOKEN") or os.environ.get("TOKEN")
    if not token:
        raise SystemExit("Set DISCORD_TOKEN environment variable.")
    bot.run(token)


if __name__ == "__main__":
    main()
